### PR TITLE
feat: add letsencrypt:active to check if active

### PR DESCRIPTION
**Pull request by boredland**
Hi there! For programmatic activation (ex. in CI) it would be nice to be able to run :enable only, if it isn't already active.

### CODE REVIEW

**Comment by josegonzalez** [comment]
This is great! Can you add usage docs to the readme?

**Comment by boredland** [comment]
Done, but still: do you have an idea why I am hitting the "not a dokku command" when I install it?

**Comment by josegonzalez** [comment]
Is the active file executable?

**Comment by boredland** [comment]
thanks for the hint. works like a charm now!

**Pull request merged**
