### PR TITLE
Clarification on requirements

### PR DESCRIPTION
**Pull request by chiedo**

### CODE REVIEW

**Comment by joshmanders** [comment]
Excuse me if I'm wrong, as I just started doing work on this plugin, so I am not completely understanding of how it works, but as far as I know it just proxies all requests to `/.well-known/acme-challenge/` right? So an app existent or not shouldn't care much, so why do we fail when it doesn't have an actual built app but only a created app?

If an app is created theoretically it should work, right?

**Comment by chiedo** [comment]
Hmmm... I'm really not sure! Lol. I've tried three different deployments with this and finally it things to work consistently by having the app running first. Any ideas? Maybe that's just a symptom?

**Comment by joshmanders** [comment]
Not exactly sure, I think it's meant to fail, but I don't see why it should matter if the app has been deployed yet or not, as long as an app is created, everything should be there for it to work.

**Comment by chiedo** [comment]
Haha,
Well my experience has been that it only works if the app is deployed.

Want to try on your end with a brand new server and no deployed (just created) apps?

**Comment by chiedo** [comment]
Hey again!

:)

Any update on this @joshmanders ? Have you been able to try it out on your end to either prove or disprove my experience?

Thanks!

**Comment by joshmanders** [comment]
Sorry forgot about this PR, I couldn't get it to work either, so let's just add the notice. :)

**Comment by chiedo** [comment]
No worries @joshmanders thanks! :)

**Pull request merged**
