### PR TITLE
Make commands consistent

### LINKED ISSUE #103: Add alias for or rename ls command
Most dokku plugin call this command `list` not a `ls`, like `mongo`, `mysql`, `redis` and etc, that's a bit inconsistent, so I would like to propose to either change the name or add alias.

I know that have different plugins have different functions and therefore can't represent the same interface, but this command looks universal enough to me to be make more consistent?

### PR DESCRIPTION
**Pull request by josegonzalez**
- rename :ls => :list
- rename default command => :apply
- show help output for default command

Closes #103

### CODE REVIEW

**Comment by fruitl00p** [comment]
I fully agree with all the changes except for the default -> `:apply` change... This feels really weird... It might just be me having to get used to this, but hey ;)

**Comment by josegonzalez** [comment]
What do you think we should rename the command to?

**Comment by fruitl00p** [comment]
If you really want to name it anything... (Which I wouldn't) it could be 'enable' or something... 

I just think the default (leaving out the command itself) works well enough... ?

**Comment by josegonzalez** [comment]
I'd really like to standardize on the command naming for all official plugins, and having the help output be default goes a long way.

Enable seems reasonable to me.

**Comment by fruitl00p** [comment]
i'm all for standardizing, but I do believe that some plugins might not have an `enable` or `apply`... (i.e. thinking of the DB pugins) So standardization will just end with having no actual default / the `help` command as default... (and the `list` / `ls` perhaps)

Anyway, all :+1: for any attempt in aligning all the (official) plugins!

**Comment by josegonzalez** [comment]
Enable is most common amongst the core, but I wasn't super sure the wording was accurate here. That said, if thats the suggestion, its better than mine :D

**Comment by josegonzalez** [comment]
I was also thinking of calling it `on` - like `trace:on` - but ditto on naming.

**Comment by fruitl00p** [comment]
on/off does have a clear / short enable/disable feel but i'd still prefer the en/dis-able options... (personally) As i feel that this more clearly ties into the plugin architecture feel... (you can `install and enable` this plugin, but you cant 'install and on` the plugin... (it would have to be 'turn-on' / 'turn-off' in that case... which is very clunky)

**Comment by josegonzalez** [comment]
Turning the plugin off would be something like:

- deleting the app's letsencrypt directory
- removing tls certificates
- rebuilding nginx

So thats one option.

**Comment by josegonzalez** [comment]
Renamed to `:enable` and added `:disable`.

**Comment by josegonzalez** [comment]
@fruitl00p mind giving it a final review? Would like to merge this before working on the cron support issue.

**Review by fruitl00p — APPROVED** [review]
LGTM :shipit: I like the clear/concise command surface 👍

**Pull request merged**
